create table users
(
    id   int generated by default as identity primary key,
    name varchar(255)
);

create table files
(
    id        int generated by default as identity primary key,
    name      varchar(255),
    file_path varchar(255)
);

create table events
(
    id      int generated by default as identity primary key,
    user_id int,
    file_id int,
    constraint fk_events_on_users foreign key (user_id) references users (id),
    constraint fk_events_on_files foreign key (file_id) references files (id)
);